# Site settings
title: Dev Blog
header-img: img/home-bg.jpg
email: marcind.blog@gmail.com
description: "Marcin Debowiak dev blog, Scala, Akka, functional programming"
baseurl: ""
url: "http://debowiak.pl"
twitter_username:
github_username:  marcindb
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
